// <auto-generated />
namespace bAnglaShoper.Com.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addProduct_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProduct_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101344331_addProduct_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
